[theme]
base = "dark"
primaryColor = "#C8102E"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#161616"
textColor = "#f2f2f2"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
